/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrustRouteImport } from './routes/_app.trust'
import { Route as AppReelsRouteImport } from './routes/_app.reels'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppComposeRouteImport } from './routes/_app.compose'
import { Route as AppChatRouteImport } from './routes/_app.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrustRoute = AppTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/compose': typeof AppComposeRoute
  '/feed': typeof AppFeedRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRoute
  '/trust': typeof AppTrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/compose': typeof AppComposeRoute
  '/feed': typeof AppFeedRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRoute
  '/trust': typeof AppTrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/compose': typeof AppComposeRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reels': typeof AppReelsRoute
  '/_app/trust': typeof AppTrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/compose'
    | '/feed'
    | '/profile'
    | '/reels'
    | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/compose'
    | '/feed'
    | '/profile'
    | '/reels'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chat'
    | '/_app/compose'
    | '/_app/feed'
    | '/_app/profile'
    | '/_app/reels'
    | '/_app/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trust': {
      id: '/_app/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AppTrustRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppComposeRoute: typeof AppComposeRoute
  AppFeedRoute: typeof AppFeedRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReelsRoute: typeof AppReelsRoute
  AppTrustRoute: typeof AppTrustRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppComposeRoute: AppComposeRoute,
  AppFeedRoute: AppFeedRoute,
  AppProfileRoute: AppProfileRoute,
  AppReelsRoute: AppReelsRoute,
  AppTrustRoute: AppTrustRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
